// <auto-generated />
using System;
using Bolao.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bolao.Infra.Migrations
{
    [DbContext(typeof(BolaoContext))]
    partial class BolaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Bolao.Domain.Models.HistoricoPontuacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DPRodada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JogadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PontuacaoRodada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RodadaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("RodadaId");

                    b.ToTable("HistoricoPontuacoes");
                });

            modelBuilder.Entity("Bolao.Domain.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistanciaPontuacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("Bolao.Domain.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GolsTimeCasa")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GolsTimeVisitante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RodadaId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TimeCasaId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TimeVisitanteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RodadaId");

                    b.HasIndex("TimeCasaId");

                    b.HasIndex("TimeVisitanteId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("Bolao.Domain.Models.Palpite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistanciaPontuacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JogadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PalpiteGolsTimeCasa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PalpiteGolsTimeFora")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("JogoId");

                    b.ToTable("Palpites");
                });

            modelBuilder.Entity("Bolao.Domain.Models.Rodada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rodadas");
                });

            modelBuilder.Entity("Bolao.Domain.Models.Time", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("Bolao.Domain.Models.HistoricoPontuacao", b =>
                {
                    b.HasOne("Bolao.Domain.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bolao.Domain.Models.Rodada", "Rodada")
                        .WithMany("HistoricoPontuacoes")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Rodada");
                });

            modelBuilder.Entity("Bolao.Domain.Models.Jogo", b =>
                {
                    b.HasOne("Bolao.Domain.Models.Rodada", "Rodada")
                        .WithMany("Jogos")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bolao.Domain.Models.Time", "TimeCasa")
                        .WithMany()
                        .HasForeignKey("TimeCasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bolao.Domain.Models.Time", "TimeVisitante")
                        .WithMany()
                        .HasForeignKey("TimeVisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rodada");

                    b.Navigation("TimeCasa");

                    b.Navigation("TimeVisitante");
                });

            modelBuilder.Entity("Bolao.Domain.Models.Palpite", b =>
                {
                    b.HasOne("Bolao.Domain.Models.Jogador", "Jogador")
                        .WithMany("Palpites")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bolao.Domain.Models.Jogo", "Jogo")
                        .WithMany("Palpites")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("Bolao.Domain.Models.Jogador", b =>
                {
                    b.Navigation("Palpites");
                });

            modelBuilder.Entity("Bolao.Domain.Models.Jogo", b =>
                {
                    b.Navigation("Palpites");
                });

            modelBuilder.Entity("Bolao.Domain.Models.Rodada", b =>
                {
                    b.Navigation("HistoricoPontuacoes");

                    b.Navigation("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
